### ISSUE TITLE
docker pull should refer to stable rather than latest

### ISSUE THREAD

**Issue by KathyReid** [mozilla/deepspeech-playbook#10]
Moved from https://github.com/JRMeyer/deepspeech-playbook/issues/32 raised by @lissyx 

docker pull mozilla/deepspeech-train:latest is going to pull latest push from master tag which not unlikely to be broken
We should rather direct people to a stable tag, e.g., v0.9.3 like mozilla/deepspeech-train:v0.9.3

@KathyReid Do you think it's good enough to point to a fixed version tag? We should be able to augment the code that push to docker hub to also make a tag for this, but it would require some work.

**Comment by KathyReid** [comment]
@lissyx I think this is a **great** idea, and you're absolutely right about `:latest` likely to be broken. 

I like using a version tag because: 

- if people need help in Discourse, it helps make it clear what version they were using 
- and it makes it clear to the user what version they are using - for example if they need to refer to the documentation (which uses the same versioning system on ReadTheDocs)

So yes +1 to this. 

Next steps: 

1. Docker Hub amendments to include version tag (@lissyx)
2. PlayBook documentation update to change from `:latest` to version tag (@KathyReid)

**Comment by lissyx** [comment]
> Docker Hub amendments to include version tag (@lissyx)

There is nothing to do, it has been done since day one of Docker Hub: https://hub.docker.com/layers/mozilla/deepspeech-train/v0.9.3/images/sha256-b07947fefa000f0b1c4068f806c38d679b73cd739b96f5cb8898d82db39cb6d0?context=explore

**Comment by KathyReid** [comment]
OK, brilliant, I will make the change in the PlayBook to refer to a tagged version, not to `:latest`
