### ISSUE TITLE
Add example to SCORER.md on how to rebuild scorer 

### ISSUE THREAD

**Issue by KathyReid** [mozilla/deepspeech-playbook#3]
Community feedback has indicated that we need a tutorial in SCORER.md on how to rebuild the scorer / language model for specific vocabulary, or a new language. This Issue is to update SCORER.md with an example of rebuilding the scorer.

**Comment by nmstoker** [comment]
Hi @KathyReid,

A while back, in the time before the scorer was in its current form and things were done with KenLM a little more directly, I'd posted here about how to work with custom vocab:
https://discourse.mozilla.org/t/tune-moziiladeepspeech-to-recognize-specific-sentences/41350/24?u=nmstoker

I could see about developing something more up-to-date from that if you like?

**Comment by KathyReid** [comment]
Yes please @nmstoker! Appreciate all the help we can get with the PlayBook :-)

**Comment by KathyReid** [comment]
@nmstoker Hi Neil, I've added an example of building a new scorer file with `KenLM` into the commit referenced above (#7b0b362), but would really appreciate another set of eyes over it. In particular I have these questions: 

- How are the `--default_alpha` and `--default_beta` values given in the example calculated? How should someone adjust these values, or does this require knowledge of `KenLM`? 

- Are there any heuristics that are relevant to know here?

**Comment by lissyx** [comment]
>     * How are the `--default_alpha` and `--default_beta` values given in the example calculated? How should someone adjust these values, or does this require knowledge of `KenLM`?

Through lm optimizer: https://github.com/mozilla/DeepSpeech/blob/385c8c769bc4aed5e6979a239591486c44f3471d/lm_optimizer.py

(sorry to insist, but also something I cover in https://github.com/common-voice/commonvoice-fr/blob/c201ff721e8d42bc0751ea3d7421d0ba8c81231e/DeepSpeech/evaluate_lm.sh https://github.com/common-voice/commonvoice-fr/blob/c201ff721e8d42bc0751ea3d7421d0ba8c81231e/DeepSpeech/run.sh#L35
