### ISSUE TITLE
Add information on checkpoint storage to TRAINING.md

### ISSUE THREAD

**Issue by KathyReid** [mozilla/deepspeech-playbook#6]
Per discussions with @JRMeyer; 

> the name of the checkpoint file is how many steps the model has taken, ever. If the model has trained for 10 epochs at 500 steps per epoch, the final checkpoints will be labeled with "5000". The checkpoint files are saved not at the end of every epoch, but at a set time interval [link]. the default is every 10 minutes

Information needed in PlayBook on: 

- naming format of checkpoint files
- how to alter the time interval for checkpointing - ie for more frequent or less frequent checkpointing - it takes up a fair amount of hard drive space so it's useful to be able to tweak it.

**Comment by lissyx** [comment]
> how to alter the time interval for checkpointing - ie for more frequent or less frequent checkpointing - it takes up a fair amount of hard drive space so it's useful to be able to tweak it.

This should be covered in `python DeepSpeech.py --helpfull`
