### ISSUE TITLE
people should refer to docker images using tags

### ISSUE THREAD

**Issue by KathyReid** [mozilla/deepspeech-playbook#9]
Moved from https://github.com/JRMeyer/deepspeech-playbook/issues/33 raised by @lissyx 

    You will need the id of the Docker image that you created when you set up your DeepSpeech training environment.

We should rather instruct people to apply tags to their image so they can e.g., docker run [...] deepspeech-local:stable.

**Comment by KathyReid** [comment]
I think this is a duplicate of #10, closing

**Comment by lissyx** [comment]
It's not a dupe, I think you pasted the wrong text from the original issue:

> You will need the id of the Docker image that you created when you set up your DeepSpeech training environment.

We should rather instruct people to apply tags to their image so they can e.g., `docker run  [...] deepspeech-local:stable`.

**Comment by KathyReid** [comment]
Aaah, sorry. Yes, good point, and sorry for the error.
